### PR TITLE
Comment popup

### PR DESCRIPTION
**Pull request by olaishola05**
# Add functionality for comment popup

- Create a module file for a modal popup
- Add structure and styling
- Add JS functionality

### CODE REVIEW

**Comment by TimmyChan99** [comment]
Hey, @netman5  you did a good job, I liked the structure and style, there is just a little issue in the form as you see in the screenshot, I suggest giving it a display flex column to solve it.

image

**Review by TimmyChan99 — CHANGES_REQUESTED** [review]
## **Changes required** ♻️ 

Hey, @netman5 you did a good job, I liked the structure and style, there is just a little issue in the form as you see in the screenshot, I suggest giving it a display flex column to solve it.

image

**Comment by olaishola05** [comment]
Thank you @TimmyChan99, honestly don't know why is like that, below is the picture of how it looks in my local machine
event-form

Not sure what to do now.

**Comment by TimmyChan99** [comment]
I think the problem with the screen size is because it looks good on screens that are below 1300px but on-screen sizes above 1300px it displays like that. So I think it would be better to just give it a display flex column and it will work on all screen sizes.

**Comment by olaishola05** [comment]
Oh! now I get it, thanks for the clarification. Applied the changes :sunglasses:

**Review by TimmyChan99 — APPROVED** [review]
## Approved 🟢 
Now it's looking good, There is nothing else to say other than, it's time to merge it

**Pull request merged**
